document.writeln("<html lang=\'en\'>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title>Document</title>");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width,initial-scale=1\'>");
document.writeln("		<link rel=\'stylesheet\' href=\'css/bootstrap.css\'>");
document.writeln("		<link rel=\'stylesheet\' href=\'css/index.css\'>");
document.writeln("		<script src=\'js/jquery.min.js\'></script>");
document.writeln("		<script src=\'js/popper.min.js\'></script>");
document.writeln("		<script src=\'js/bootstrap.min.js\'></script>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div class=\'container\'>");
document.writeln("			<div class=\'navbar navbar-light navbar-expand-md py-3\'>");
document.writeln("				<!-- 1.从来都不隐藏的logo -->");
document.writeln("				<a href=\'index.html\' class=\'navbar-brand\'><img class=\'logo\' src=\'img/logo.png\' ></a>");
document.writeln("				<!-- 2.按钮 小屏显示，大屏隐藏，折叠的触发按钮 -->");
document.writeln("				<button class=\'navbar-toggler\' data-toggle=\'collapse\' data-target=\'#d1\'>");
document.writeln("					<span class=\'navbar-toggler-icon\'></span>");
document.writeln("				</button>");
document.writeln("				<!-- 3.菜单 小屏隐藏，大屏显示");
document.writeln("										小屏纵向，大屏横向-->");
document.writeln("				<div id=\'d1\' class=\'collapse navbar-collapse pl-4\'>");
document.writeln("					<ul class=\'navbar-nav\'>");
document.writeln("						<li class=\'nav-item mt-sm-1 mt-md-0\'>");
document.writeln("							<a class=\'nav-link\' href=\'index.html\'>首页</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-item\'>");
document.writeln("							<a class=\'nav-link\' href=\'page.html\'>装修效果图</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-item\'>");
document.writeln("							<a class=\'nav-link\' href=\'case_list.html\'>装修案例</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-item\'>");
document.writeln("							<a class=\'nav-link\' href=\'#\'>装修知识</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-item\'>");
document.writeln("							<a class=\'nav-link\' href=\'#\'>关于我们</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("				<div class=\'text-center pr-4 d-0-none d-lg-block\'>");
document.writeln("					<span class=\'font-24\'>400-500-6000</span><br>");
document.writeln("					<span class=\'font-15\'>2 4 小 时 服 务 热 线</span>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</body>");
document.writeln("</html>");